stages:
  - build
  - deploy

variables:
  VERSION: "1.0-app"

create-images:
  stage: build
  tags:
    - AWS
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t fkamag/tcc-escola-da-nuvem:$VERSION app/.
    - docker push fkamag/tcc-escola-da-nuvem:$VERSION
  
run_docker:
  stage: deploy
  tags: 
    - AWS
  before_script:
    - docker rm -f app-docker

  script:
    - docker pull fkamag/tcc-escola-da-nuvem:$VERSION
    - docker run -dti -p 80:80 --name app-docker fkamag/tcc-escola-da-nuvem:$VERSION
